@Library("shared-library") _

pipeline {
   agent any

   stages {
      stage('Hello') {
         steps {
            echo 'Hello World'
         }
      }
      stage('Hello from library') {
         steps {
            helloWorld()
         }
      }
   }
}
